try:
    n=10
    print(n)
    raise ValueError
except:
    print('Exception Occurred')
